In [1]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout, Conv2D, MaxPool2D, Flatten
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.pipeline import Pipeline
from keras.utils import to_categorical
from sklearn.datasets import load_files       
from keras.utils import np_utils
import pandas as pd
from glob import glob
import zipfile
from keras.preprocessing import image 
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline

Using TensorFlow backend.


In [5]:
img = image.load_img("/Users/Achaea/GA/Dog Kaggle/train/0a0c223352985ec154fd604d7ddceabd.jpg", 
                     target_size=(255,255)) 
img = image.img_to_array(img)

In [7]:
df = pd.read_csv('/Users/Achaea/GA/Dog Kaggle/labels.csv')

In [8]:
df["url"] = "/Users/Achaea/GA/Dog Kaggle/train/"+df["id"]+".jpg"
df[["url"]].head(3)

url
0  /Users/Achaea/GA/Dog Kaggle/train/000bec180eb1...
1  /Users/Achaea/GA/Dog Kaggle/train/001513dfcb2f...
2  /Users/Achaea/GA/Dog Kaggle/train/001cdf01b096...

In [9]:
df.loc[4]

id                        0021f9ceb3235effd7fcde7f7538ed62
breed                                     golden_retriever
url      /Users/Achaea/GA/Dog Kaggle/train/0021f9ceb323...
Name: 4, dtype: object

In [10]:
df.loc[5]["id"]

'002211c81b498ef88e1b40b9abf84e1d'

In [11]:
df.tail(3)

id                     breed  \
10219  ffe2ca6c940cddfee68fa3cc6c63213f                  airedale   
10220  ffe5f6d8e2bff356e9482a80a6e29aac        miniature_pinscher   
10221  fff43b07992508bc822f33d8ffd902ae  chesapeake_bay_retriever   

                                                     url  
10219  /Users/Achaea/GA/Dog Kaggle/train/ffe2ca6c940c...  
10220  /Users/Achaea/GA/Dog Kaggle/train/ffe5f6d8e2bf...  
10221  /Users/Achaea/GA/Dog Kaggle/train/fff43b079925...

In [12]:
df.loc[[10221]]

id                     breed  \
10221  fff43b07992508bc822f33d8ffd902ae  chesapeake_bay_retriever   

                                                     url  
10221  /Users/Achaea/GA/Dog Kaggle/train/fff43b079925...

In [13]:
len(df)

10222

In [14]:
img=[]
for i in df ["id"]:
    path="/Users/Achaea/GA/Dog Kaggle/train/"+i+".jpg"
    img.append(np.asarray(image.load_img(path,target_size=(255,255))))
    #img.append(image.load_img(path,target_size=(255,255)))

    

In [88]:
def rgb (colors):
    return (colors[0]+colors[1]+colors[2])/3.0

def rgb_to_greyscale(input_image):
    output_image=[]
    for j in input_image:
        temp_xlist=[]
        for k in j:
            temp_xlist.append(rgb(k))
        output_image.append(temp_xlist)
    return output_image
            

In [ ]:
#imgsub=img[665:667]

greyscale = []
for i in img:
    greyscale.append(rgb_to_greyscale(i))
    
    
#     greyscale.append(rgb(i))

        

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in ubyte_scalars
  


In [80]:
img[666][0]

array([[102,  46,  33],
       [103,  47,  34],
       [103,  47,  34],
       [104,  48,  35],
       [103,  47,  34],
       [102,  46,  33],
       [100,  44,  31],
       [ 99,  43,  30],
       [100,  44,  31],
       [100,  44,  31],
       [102,  46,  33],
       [ 98,  42,  29],
       [ 96,  40,  27],
       [ 97,  41,  28],
       [ 99,  43,  30],
       [101,  45,  32],
       [103,  47,  34],
       [105,  49,  36],
       [106,  50,  37],
       [107,  51,  38],
       [107,  51,  38],
       [107,  51,  38],
       [104,  49,  35],
       [100,  47,  31],
       [100,  47,  31],
       [101,  48,  32],
       [101,  48,  32],
       [102,  49,  33],
       [103,  48,  33],
       [104,  48,  33],
       [103,  47,  32],
       [102,  46,  31],
       [102,  46,  31],
       [103,  45,  31],
       [105,  47,  33],
       [106,  47,  33],
       [106,  47,  33],
       [107,  48,  34],
       [107,  48,  34],
       [108,  48,  34],
       [110,  48,  35],
       [110,  48

In [86]:
junk=greyscale(img[666])
#img[666][4][5]

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in ubyte_scalars
  


In [84]:
len(junk)
junk[254]

[54.0,
 54.0,
 53.666666666666664,
 54.666666666666664,
 54.333333333333336,
 54.333333333333336,
 55.333333333333336,
 55.333333333333336,
 55.333333333333336,
 55.333333333333336,
 56.333333333333336,
 54.0,
 52.333333333333336,
 52.666666666666664,
 52.666666666666664,
 53.333333333333336,
 54.0,
 54.666666666666664,
 55.333333333333336,
 56.0,
 56.0,
 56.0,
 53.666666666666664,
 50.0,
 51.0,
 51.666666666666664,
 52.0,
 54.0,
 54.0,
 54.333333333333336,
 55.333333333333336,
 55.666666666666664,
 55.666666666666664,
 54.666666666666664,
 52.333333333333336,
 56.333333333333336,
 60.0,
 62.0,
 60.0,
 57.333333333333336,
 55.333333333333336,
 56.333333333333336,
 56.0,
 54.0,
 51.0,
 53.666666666666664,
 53.333333333333336,
 49.0,
 41.666666666666664,
 38.666666666666664,
 38.666666666666664,
 40.0,
 38.0,
 40.0,
 49.333333333333336,
 72.333333333333329,
 2.3333333333333335,
 8.0,
 83.333333333333329,
 73.666666666666671,
 65.333333333333329,
 60.666666666666664,
 59.0,
 58.6666666666

In [64]:
greyscale[0]

[[3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,


In [53]:
len(img[666][0])

255

In [54]:
img[666][0]

array([[102,  46,  33],
       [103,  47,  34],
       [103,  47,  34],
       [104,  48,  35],
       [103,  47,  34],
       [102,  46,  33],
       [100,  44,  31],
       [ 99,  43,  30],
       [100,  44,  31],
       [100,  44,  31],
       [102,  46,  33],
       [ 98,  42,  29],
       [ 96,  40,  27],
       [ 97,  41,  28],
       [ 99,  43,  30],
       [101,  45,  32],
       [103,  47,  34],
       [105,  49,  36],
       [106,  50,  37],
       [107,  51,  38],
       [107,  51,  38],
       [107,  51,  38],
       [104,  49,  35],
       [100,  47,  31],
       [100,  47,  31],
       [101,  48,  32],
       [101,  48,  32],
       [102,  49,  33],
       [103,  48,  33],
       [104,  48,  33],
       [103,  47,  32],
       [102,  46,  31],
       [102,  46,  31],
       [103,  45,  31],
       [105,  47,  33],
       [106,  47,  33],
       [106,  47,  33],
       [107,  48,  34],
       [107,  48,  34],
       [108,  48,  34],
       [110,  48,  35],
       [110,  48

In [101]:
img[0]
df["img"]=img
# df.head(3)

In [102]:
df.dtypes

id       object
breed    object
url      object
img      object
dtype: object

In [103]:
y=df["breed"]
y.shape

(10222,)

In [104]:
X=df["img"]
X.shape

(10222,)

In [105]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=75)

In [106]:
print(X_train.shape)
print (X_test.shape)

(6848,)
(3374,)


In [107]:
print (y_test.shape)
print (y_train.shape)

(3374,)
(6848,)


In [108]:
img[666]

array([[[102,  46,  33],
        [103,  47,  34],
        [103,  47,  34],
        ..., 
        [ 86,  50,  31],
        [ 86,  48,  30],
        [ 87,  48,  31]],

       [[102,  46,  33],
        [103,  47,  34],
        [103,  47,  34],
        ..., 
        [ 86,  50,  31],
        [ 86,  48,  30],
        [ 87,  48,  31]],

       [[103,  47,  34],
        [104,  48,  35],
        [104,  48,  35],
        ..., 
        [ 86,  49,  31],
        [ 86,  48,  31],
        [ 88,  49,  32]],

       ..., 
       [[ 88,  52,  35],
        [ 88,  52,  35],
        [ 88,  52,  35],
        ..., 
        [ 76,  98, 123],
        [ 64,  86, 112],
        [ 59,  80, 107]],

       [[ 89,  44,  29],
        [ 89,  44,  29],
        [ 89,  44,  29],
        ..., 
        [ 61,  86, 114],
        [ 52,  76, 106],
        [ 49,  73, 104]],

       [[ 93,  41,  28],
        [ 92,  42,  28],
        [ 91,  42,  28],
        ..., 
        [ 55,  82, 112],
        [ 48,  74, 106],
        [ 46,  72,

In [109]:
model = Sequential()
model.add(Dense(X_train, input_dim=X_train, activation='relu'))
model.add(Dense(y.shape[1], activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=25, batch_size=100)

TypeError: cannot convert the series to <class 'int'>